### PR TITLE
update lad-book pro progress

### PR DESCRIPTION
**Pull request by keven2116**
Modify the dir structure of the lad-book tree.
update the project planning time node.
add lad-book submission specification.

### CODE REVIEW

**Review by keven2116 — COMMENTED** [review]
please using .placeholder replace .gitignore 
delete vim backup file.

**Review by DeviosLang — APPROVED** [review]

**Comment by DeviosLang** [comment]
review没有问题

**Review by DeviosLang — APPROVED** [review]

**Comment by DeviosLang** [comment]
review没有问题

**Comment by lzufalcon** [comment]
@bjwrkj 提交commit时记得带 -s 选项加入签名。

**Comment by lzufalcon** [comment]
@bjwrkj 手工调整后已经合并。Thanks.

**Pull request closed without merging**
